# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bruce < Formula
  desc ""
  homepage "https://github.com/borealisgroup/homebrew-tools"
  version "1.1.16"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/borealisgroup/homebrew-tools/releases/download/v1.1.16/bruce_1.1.16_Darwin_arm64.tar.gz"
      sha256 "d436fcf31b11928838c0703f02216fad771236c284525cc25c22164a7d47d824"

      def install
        bin.install "bruce"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/borealisgroup/homebrew-tools/releases/download/v1.1.16/bruce_1.1.16_Darwin_x86_64.tar.gz"
      sha256 "b805a5f9cdc525f3025d4a1a852268ed0f4240d32256290f07457762549636a5"

      def install
        bin.install "bruce"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/borealisgroup/homebrew-tools/releases/download/v1.1.16/bruce_1.1.16_Linux_x86_64.tar.gz"
      sha256 "f613c063916ca2127e616c4102780b455ae47079190ce5b214a2b08f7b1e2928"

      def install
        bin.install "bruce"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borealisgroup/homebrew-tools/releases/download/v1.1.16/bruce_1.1.16_Linux_arm64.tar.gz"
      sha256 "abaef5bd12d55b14a60d4523bb3e7664f08c3259ef26c9e940fb481c6b072961"

      def install
        bin.install "bruce"
      end
    end
  end
end
