# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bruce < Formula
  desc ""
  homepage "https://github.com/borealisgroup/homebrew-tools"
  version "1.1.24"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/borealisgroup/homebrew-tools/releases/download/v1.1.24/bruce_1.1.24_Darwin_arm64.tar.gz"
      sha256 "1e7f438c64b242baf0239d5df042734ea1898cbaa6cde85fa0265329b0b1dabb"

      def install
        bin.install "bruce"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/borealisgroup/homebrew-tools/releases/download/v1.1.24/bruce_1.1.24_Darwin_x86_64.tar.gz"
      sha256 "72222ba54d20914a45a0b6f6c66ef84aa7b97fa53fc50e5d56bfc1b81a4fdf2f"

      def install
        bin.install "bruce"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/borealisgroup/homebrew-tools/releases/download/v1.1.24/bruce_1.1.24_Linux_arm64.tar.gz"
      sha256 "7ad7d551952c20f9c4334d00a8b4e4d4823030c3b092f06da97eb1576598bb79"

      def install
        bin.install "bruce"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/borealisgroup/homebrew-tools/releases/download/v1.1.24/bruce_1.1.24_Linux_x86_64.tar.gz"
      sha256 "55e157a2f875d6e90cf60fdabe0e46fdd1c37c7fea45f66c76513d68b5ac978a"

      def install
        bin.install "bruce"
      end
    end
  end
end
